require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BonusSchemesController do

  # This should return the minimal set of attributes required to create a valid
  # BonusScheme. As you add validations to BonusScheme, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "reason" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BonusSchemesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all bonus_schemes as @bonus_schemes" do
      bonus_scheme = BonusScheme.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bonus_schemes).should eq([bonus_scheme])
    end
  end

  describe "GET show" do
    it "assigns the requested bonus_scheme as @bonus_scheme" do
      bonus_scheme = BonusScheme.create! valid_attributes
      get :show, {:id => bonus_scheme.to_param}, valid_session
      assigns(:bonus_scheme).should eq(bonus_scheme)
    end
  end

  describe "GET new" do
    it "assigns a new bonus_scheme as @bonus_scheme" do
      get :new, {}, valid_session
      assigns(:bonus_scheme).should be_a_new(BonusScheme)
    end
  end

  describe "GET edit" do
    it "assigns the requested bonus_scheme as @bonus_scheme" do
      bonus_scheme = BonusScheme.create! valid_attributes
      get :edit, {:id => bonus_scheme.to_param}, valid_session
      assigns(:bonus_scheme).should eq(bonus_scheme)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BonusScheme" do
        expect {
          post :create, {:bonus_scheme => valid_attributes}, valid_session
        }.to change(BonusScheme, :count).by(1)
      end

      it "assigns a newly created bonus_scheme as @bonus_scheme" do
        post :create, {:bonus_scheme => valid_attributes}, valid_session
        assigns(:bonus_scheme).should be_a(BonusScheme)
        assigns(:bonus_scheme).should be_persisted
      end

      it "redirects to the created bonus_scheme" do
        post :create, {:bonus_scheme => valid_attributes}, valid_session
        response.should redirect_to(BonusScheme.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bonus_scheme as @bonus_scheme" do
        # Trigger the behavior that occurs when invalid params are submitted
        BonusScheme.any_instance.stub(:save).and_return(false)
        post :create, {:bonus_scheme => { "reason" => "invalid value" }}, valid_session
        assigns(:bonus_scheme).should be_a_new(BonusScheme)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BonusScheme.any_instance.stub(:save).and_return(false)
        post :create, {:bonus_scheme => { "reason" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bonus_scheme" do
        bonus_scheme = BonusScheme.create! valid_attributes
        # Assuming there are no other bonus_schemes in the database, this
        # specifies that the BonusScheme created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BonusScheme.any_instance.should_receive(:update_attributes).with({ "reason" => "MyString" })
        put :update, {:id => bonus_scheme.to_param, :bonus_scheme => { "reason" => "MyString" }}, valid_session
      end

      it "assigns the requested bonus_scheme as @bonus_scheme" do
        bonus_scheme = BonusScheme.create! valid_attributes
        put :update, {:id => bonus_scheme.to_param, :bonus_scheme => valid_attributes}, valid_session
        assigns(:bonus_scheme).should eq(bonus_scheme)
      end

      it "redirects to the bonus_scheme" do
        bonus_scheme = BonusScheme.create! valid_attributes
        put :update, {:id => bonus_scheme.to_param, :bonus_scheme => valid_attributes}, valid_session
        response.should redirect_to(bonus_scheme)
      end
    end

    describe "with invalid params" do
      it "assigns the bonus_scheme as @bonus_scheme" do
        bonus_scheme = BonusScheme.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BonusScheme.any_instance.stub(:save).and_return(false)
        put :update, {:id => bonus_scheme.to_param, :bonus_scheme => { "reason" => "invalid value" }}, valid_session
        assigns(:bonus_scheme).should eq(bonus_scheme)
      end

      it "re-renders the 'edit' template" do
        bonus_scheme = BonusScheme.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BonusScheme.any_instance.stub(:save).and_return(false)
        put :update, {:id => bonus_scheme.to_param, :bonus_scheme => { "reason" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bonus_scheme" do
      bonus_scheme = BonusScheme.create! valid_attributes
      expect {
        delete :destroy, {:id => bonus_scheme.to_param}, valid_session
      }.to change(BonusScheme, :count).by(-1)
    end

    it "redirects to the bonus_schemes list" do
      bonus_scheme = BonusScheme.create! valid_attributes
      delete :destroy, {:id => bonus_scheme.to_param}, valid_session
      response.should redirect_to(bonus_schemes_url)
    end
  end

end
